import { AlertTriangle, BarChart3, Download, FileText, Key, Lightbulb, Target, TrendingUp } from 'lucide-react';
import { useState } from 'react';
import toast from 'react-hot-toast';
import FileUpload from '../components/FileUpload';
import { useApiKey } from '../context/ApiKeyContext';
import { DocumentProcessor } from '../services/documentProcessor';
import { ResumeAnalyzer as ResumeAnalyzerService } from '../services/resumeAnalyzer';
import { TextFormatter } from '../utils/textFormatter';

const ResumeAnalyzer = () => {
  const { geminiApiKey, updateGeminiApiKey, hasGeminiKey, isFromEnv, canModifyKey } = useApiKey();
  const [tempApiKey, setTempApiKey] = useState('');
  const [file, setFile] = useState(null);
  const [processing, setProcessing] = useState(false);
  const [analysisResults, setAnalysisResults] = useState(null);
  const [activeTab, setActiveTab] = useState('summary');

  const handleApiKeySubmit = (e) => {
    e.preventDefault();
    if (!canModifyKey) {
      if (isFromEnv) {
        toast.error('API key is configured via environment variables and cannot be changed.');
      } else {
        toast.error('Local storage fallback is disabled. Please configure API key in environment variables.');
      }
      return;
    }
    
    if (tempApiKey.trim()) {
      updateGeminiApiKey(tempApiKey.trim());
      setTempApiKey('');
      toast.success('API key saved successfully!');
    }
  };

  const handleFileSelect = (selectedFile) => {
    setFile(selectedFile);
    if (analysisResults) {
      setAnalysisResults(null);
    }
  };

  const handleAnalyze = async () => {
    if (!file || !hasGeminiKey) {
      toast.error('Please upload a file and provide a valid API key');
      return;
    }

    setProcessing(true);
    const loadingToast = toast.loading('Analyzing your resume...');

    try {
      // Get file type for user feedback
      const fileType = DocumentProcessor.getFileType(file);
      const fileTypeText = fileType.toUpperCase();
      
      // Step 1: Process Document (PDF or DOCX)
      toast.loading(`Extracting text from ${fileTypeText}...`, { id: loadingToast });
      const documentData = await DocumentProcessor.processResumeDocument(file);
      
      // Step 2: Analyze with Gemini
      toast.loading('Performing AI analysis...', { id: loadingToast });
      const analyzer = new ResumeAnalyzerService(geminiApiKey);
      const analysis = await analyzer.performCompleteAnalysis(documentData.chunks);
      
      // Debug: Log to see what we get from analysis
      console.log('Raw analysis:', analysis);
      
      // Use raw analysis for now to test
      const results = {
        ...analysis,
        documentData,
        fileName: file.name,
        fileType: fileType
      };
      
      setAnalysisResults(results);
      toast.success('Analysis completed successfully!', { id: loadingToast });
      
    } catch (error) {
      console.error('Analysis error:', error);
      toast.error(error.message || 'Failed to analyze resume', { id: loadingToast });
    } finally {
      setProcessing(false);
    }
  };

  const downloadReport = () => {
    if (!analysisResults) return;
    
    const report = `
RESUME ANALYSIS REPORT
Generated on: ${new Date().toLocaleString()}
File: ${analysisResults.fileName}

OVERALL SCORE: ${analysisResults.rating.totalScore || analysisResults.rating.overallScore}/10
GRADE: ${analysisResults.rating.grade || 'N/A'}

PROFESSIONAL SUMMARY:
${analysisResults.professionalSummary}

DETAILED ANALYSIS:

SUMMARY:
${analysisResults.summary}

STRENGTHS:
${analysisResults.strengths}

AREAS FOR IMPROVEMENT:
${analysisResults.weaknesses}

JOB TITLE SUGGESTIONS:
${analysisResults.jobTitles}

PROFESSIONAL RATING BREAKDOWN (Based on Recruiter Standards):
- Content Quality: ${analysisResults.rating.contentQuality || 'N/A'}/2
- Structure & Organization: ${analysisResults.rating.structureOrganization || 'N/A'}/2
- Formatting & Design: ${analysisResults.rating.formattingDesign || 'N/A'}/2
- Impact & Language: ${analysisResults.rating.impactLanguage || 'N/A'}/2
- ATS Compatibility: ${analysisResults.rating.atsCompatibility || 'N/A'}/2

${analysisResults.rating.improvements && analysisResults.rating.improvements.length > 0 ? `
KEY IMPROVEMENT AREAS:
${analysisResults.rating.improvements.map(improvement => `- ${improvement}`).join('\n')}
` : ''}
---
Generated by AI Resume Analyzer - GenAI Hackathon 2025
    `;
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `resume-analysis-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded successfully!');
  };

  const getScoreRing = (score) => {
    if (score >= 8) return 'text-green-500';
    if (score >= 6) return 'text-yellow-500';
    return 'text-red-500';
  };

  const tabs = [
    { id: 'summary', label: 'Summary', icon: FileText, color: 'blue', description: 'Overall resume analysis' },
    { id: 'strengths', label: 'Strengths', icon: TrendingUp, color: 'green', description: 'Key advantages & skills' },
    { id: 'weaknesses', label: 'Improvements', icon: AlertTriangle, color: 'orange', description: 'Areas to enhance' },
    { id: 'jobs', label: 'Job Suggestions', icon: Target, color: 'purple', description: 'Recommended positions' },
    { id: 'rating', label: 'Rating', icon: BarChart3, color: 'indigo', description: 'Professional scoring' }
  ];

  if (!hasGeminiKey) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 via-blue-50 to-indigo-100 flex items-center justify-center p-4">
        <div className="max-w-lg w-full bg-white/80 backdrop-blur-md rounded-2xl shadow-2xl p-8 border border-white/20">
          <div className="text-center mb-6">
            <div className="w-20 h-20 bg-gradient-to-br from-blue-500 via-purple-500 to-indigo-600 rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-105">
              <Key className="w-10 h-10 text-white" />
            </div>
            <h2 className="text-2xl font-bold bg-gradient-to-r from-blue-600 via-purple-600 to-indigo-600 bg-clip-text text-transparent mb-2">API Key Configuration</h2>
            <p className="text-gray-600 leading-relaxed">
              Configure your Google Gemini API key to start analyzing resumes with AI-powered insights
            </p>
          </div>

          {/* Environment Setup Instructions */}
          <div className="mb-6 p-4 bg-gradient-to-r from-green-50 to-emerald-50 rounded-xl border border-green-200/50">
            <h3 className="font-semibold text-green-800 mb-2 flex items-center">
              <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
              </svg>
              Recommended: Environment Variables
            </h3>
            <div className="text-sm text-green-700 space-y-2">
              <p>1. Create or edit <code className="bg-green-200/50 px-2 py-1 rounded">.env</code> file in project root</p>
              <p>2. Add: <code className="bg-green-200/50 px-2 py-1 rounded">REACT_APP_GEMINI_API_KEY=your_api_key</code></p>
              <p>3. Restart the development server</p>
              <p className="text-xs opacity-80">✅ More secure and won't be committed to version control</p>
            </div>
          </div>
          
          {canModifyKey ? (
            <>
              <div className="mb-4 p-3 bg-amber-50 rounded-lg border border-amber-200">
                <p className="text-xs text-amber-700">
                  <strong>Fallback Mode:</strong> You can temporarily enter your API key below, but environment variables are recommended for security.
                </p>
              </div>
              
              <form onSubmit={handleApiKeySubmit} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Google Gemini API Key (Temporary)
                  </label>
                  <input
                    type="password"
                    value={tempApiKey}
                    onChange={(e) => setTempApiKey(e.target.value)}
                    placeholder="Enter your Gemini API key..."
                    className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 hover:border-gray-400"
                    required
                  />
                </div>
                <button
                  type="submit"
                  className="w-full bg-gradient-to-r from-blue-600 to-purple-600 text-white py-3 px-4 rounded-xl hover:from-blue-700 hover:to-purple-700 transition-all duration-200 transform hover:scale-105 font-medium shadow-lg hover:shadow-xl"
                >
                  Save API Key (Temporary)
                </button>
              </form>
            </>
          ) : (
            <div className="p-4 bg-red-50 rounded-xl border border-red-200">
              <h3 className="font-semibold text-red-800 mb-2">Environment Configuration Required</h3>
              <p className="text-sm text-red-700">
                Local storage fallback is disabled. Please configure your API key using environment variables as shown above.
              </p>
            </div>
          )}
          
          <div className="mt-6 p-4 bg-blue-50/80 rounded-xl border border-blue-200/50">
            <p className="text-xs text-blue-700 leading-relaxed">
              <strong>Get API Key:</strong> Visit <a href="https://ai.google.dev/" target="_blank" rel="noopener noreferrer" className="underline hover:text-blue-800">Google AI Studio</a> to create your free Gemini API key.
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      <div className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 via-purple-600 to-indigo-600 bg-clip-text text-transparent mb-2">Resume Analyzer</h1>
          <p className="text-gray-600 text-lg">
            Upload your resume and get AI-powered insights to improve your career prospects
          </p>
          
          {/* Status Indicators */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6">
            <div className={`flex items-center space-x-3 p-4 rounded-lg border ${
              hasGeminiKey 
                ? 'bg-green-50 border-green-200' 
                : 'bg-red-50 border-red-200'
            }`}>
              <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${
                hasGeminiKey ? 'bg-green-100' : 'bg-red-100'
              }`}>
                <Key className={`w-4 h-4 ${hasGeminiKey ? 'text-green-600' : 'text-red-600'}`} />
              </div>
              <div className="flex-1">
                <div className="flex items-center space-x-2">
                  <span className="text-sm font-medium text-gray-900">API Key</span>
                  {hasGeminiKey && <span className="text-green-500 text-xs">✓</span>}
                  {!hasGeminiKey && <span className="text-red-500 text-xs">✗</span>}
                  {isFromEnv && <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded">ENV</span>}
                </div>
                <p className="text-xs text-gray-600">
                  {hasGeminiKey ? (isFromEnv ? 'Environment Variable' : 'Locally Stored') : 'Not Configured'}
                </p>
              </div>
            </div>
            
            <div className={`flex items-center space-x-3 p-4 rounded-lg border ${
              file 
                ? 'bg-green-50 border-green-200' 
                : 'bg-gray-50 border-gray-200'
            }`}>
              <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${
                file ? 'bg-green-100' : 'bg-gray-100'
              }`}>
                <FileText className={`w-4 h-4 ${file ? 'text-green-600' : 'text-gray-500'}`} />
              </div>
              <div className="flex-1">
                <div className="flex items-center space-x-2">
                  <span className="text-sm font-medium text-gray-900">Resume File</span>
                  {file && <span className="text-green-500 text-xs">✓</span>}
                </div>
                <p className="text-xs text-gray-600 truncate">
                  {file ? file.name : 'No file selected'}
                </p>
              </div>
            </div>
            
            <div className={`flex items-center space-x-3 p-4 rounded-lg border ${
              hasGeminiKey && file 
                ? 'bg-blue-50 border-blue-200' 
                : 'bg-gray-50 border-gray-200'
            }`}>
              <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${
                hasGeminiKey && file ? 'bg-blue-100' : 'bg-gray-100'
              }`}>
                <BarChart3 className={`w-4 h-4 ${hasGeminiKey && file ? 'text-blue-600' : 'text-gray-500'}`} />
              </div>
              <div className="flex-1">
                <div className="flex items-center space-x-2">
                  <span className="text-sm font-medium text-gray-900">Analysis</span>
                  {hasGeminiKey && file && <span className="text-blue-500 text-xs">✓</span>}
                </div>
                <p className="text-xs text-gray-600">
                  {hasGeminiKey && file ? 'Ready to Analyze' : 'Setup Required'}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Upload Section */}
        <div className="bg-white/80 backdrop-blur-md rounded-2xl shadow-xl p-8 mb-8 border border-white/20 hover:shadow-2xl transition-all duration-300">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-semibold text-gray-900 flex items-center">
              <FileText className="w-6 h-6 mr-3 text-blue-600" />
              Upload Resume
            </h2>
            
            {/* API Key Quick Setup */}
            {!hasGeminiKey && canModifyKey && (
              <div className="flex items-center space-x-2">
                <form onSubmit={handleApiKeySubmit} className="flex items-center space-x-2">
                  <input
                    type="password"
                    placeholder="Enter Gemini API Key (Temporary)"
                    value={tempApiKey}
                    onChange={(e) => setTempApiKey(e.target.value)}
                    className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                  <button
                    type="submit"
                    className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 transition-colors"
                  >
                    Save
                  </button>
                </form>
              </div>
            )}
            
            {!hasGeminiKey && !canModifyKey && (
              <div className="flex items-center space-x-2 text-sm text-amber-700 bg-amber-50 px-3 py-2 rounded-lg border border-amber-200">
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
                <span>Configure API key in .env file</span>
              </div>
            )}
          </div>
          
          <FileUpload 
            onFileSelect={handleFileSelect} 
            isProcessing={processing} 
          />
          
          {file && !processing && (
            <div className="mt-6 flex justify-center">
              <button
                onClick={handleAnalyze}
                disabled={processing || !hasGeminiKey}
                className="bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white px-8 py-3 rounded-lg disabled:cursor-not-allowed transition-colors duration-200 flex items-center space-x-3 font-medium shadow-sm hover:shadow-md"
              >
                <BarChart3 className="w-5 h-5" />
                <span>Analyze Resume</span>
              </button>
            </div>
          )}
        </div>

        {/* Results Section */}
        {analysisResults && (
          <div className="space-y-8">
            {/* Analysis Overview */}
            <div className="bg-white rounded-2xl shadow-lg border border-gray-200">
              <div className="flex justify-between items-center p-6 border-b border-gray-200">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-blue-600 rounded-lg flex items-center justify-center">
                    <BarChart3 className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h2 className="text-xl font-semibold text-gray-900">Analysis Results</h2>
                    <p className="text-sm text-gray-600">Comprehensive resume evaluation</p>
                  </div>
                </div>
                <button
                  onClick={downloadReport}
                  className="flex items-center space-x-2 px-4 py-2 text-blue-600 bg-blue-50 hover:bg-blue-100 rounded-lg font-medium transition-colors duration-200"
                >
                  <Download className="w-4 h-4" />
                  <span>Download Report</span>
                </button>
              </div>
              
              <div className="p-6">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                  <div className="text-center p-4 bg-blue-50 rounded-lg border border-blue-100">
                    <div className={`text-3xl font-bold mb-1 ${getScoreRing(analysisResults.rating.totalScore || analysisResults.rating.overallScore)}`}>
                      {analysisResults.rating.totalScore || analysisResults.rating.overallScore}/10
                    </div>
                    <div className="text-sm text-gray-600 font-medium">Overall Score</div>
                  </div>
                  <div className="text-center p-4 bg-green-50 rounded-lg border border-green-100">
                    <div className="text-3xl font-bold text-gray-900 mb-1">
                      {analysisResults.documentData.analysis.wordCount}
                    </div>
                    <div className="text-sm text-gray-600 font-medium">Words</div>
                  </div>
                  <div className="text-center p-4 bg-purple-50 rounded-lg border border-purple-100">
                    <div className="text-3xl font-bold text-gray-900 mb-1">
                      {analysisResults.documentData.metadata.pageCount}
                    </div>
                    <div className="text-sm text-gray-600 font-medium">
                      {analysisResults.fileType === 'pdf' ? 'Pages' : 'Document'}
                    </div>
                  </div>
                  <div className="text-center p-4 bg-orange-50 rounded-lg border border-orange-100">
                    <div className="text-3xl font-bold text-gray-900 mb-1">
                      {analysisResults.documentData.analysis.estimatedReadingTime}m
                    </div>
                    <div className="text-sm text-gray-600 font-medium">Read Time</div>
                  </div>
                </div>
              </div>
            </div>

            {/* Professional Summary */}
            <div className="bg-white rounded-2xl border border-gray-200 shadow-lg">
              <div className="p-6">
                <div className="mb-6 pb-4 border-b border-gray-100">
                  <div className="flex items-center space-x-3">
                    <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
                      <Lightbulb className="w-4 h-4 text-white" />
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-gray-900">Professional Summary</h3>
                      <p className="text-sm text-gray-500">AI-generated insights about your profile</p>
                    </div>
                  </div>
                </div>
                <FormattedContent content={analysisResults.professionalSummary} />
              </div>
            </div>

            {/* Navigation Tabs */}
            <div className="bg-white rounded-2xl shadow-lg border border-gray-200 overflow-hidden">
              <div className="bg-gray-50 border-b border-gray-200">
                <nav className="flex">
                  {tabs.map((tab) => {
                    const isActive = activeTab === tab.id;
                    
                    return (
                      <button
                        key={tab.id}
                        onClick={() => setActiveTab(tab.id)}
                        className={`flex-1 px-6 py-4 text-sm font-medium transition-all duration-200 border-b-2 ${
                          isActive
                            ? 'border-blue-600 bg-white text-blue-600 shadow-sm'
                            : 'border-transparent text-gray-600 hover:text-gray-900 hover:bg-gray-100'
                        }`}
                      >
                        <div className="flex items-center justify-center space-x-2">
                          <tab.icon className={`w-4 h-4 ${isActive ? 'text-blue-600' : 'text-gray-500'}`} />
                          <span>{tab.label}</span>
                        </div>
                        {tab.description && (
                          <div className="text-xs text-gray-500 mt-1 hidden sm:block">
                            {tab.description}
                          </div>
                        )}
                      </button>
                    );
                  })}
                </nav>
              </div>

              <div className="p-6 bg-white min-h-[500px]">
                {activeTab === 'summary' && (
                  <FormattedContent content={analysisResults.summary} />
                )}

                {activeTab === 'strengths' && (
                  <FormattedContent content={analysisResults.strengths} />
                )}

                {activeTab === 'weaknesses' && (
                  <FormattedContent content={analysisResults.weaknesses} />
                )}

                {activeTab === 'jobs' && (
                  <JobRecommendations content={analysisResults.jobTitles} />
                )}

                {activeTab === 'rating' && (
                  <EnhancedResumeRating rating={analysisResults.rating} />
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// Enhanced Resume Rating Component with visual indicators
const EnhancedResumeRating = ({ rating }) => {
  if (!rating) return (
    <div className="flex items-center justify-center py-12">
      <div className="text-center">
        <BarChart3 className="w-12 h-12 text-gray-400 mx-auto mb-3" />
        <p className="text-gray-500 font-medium">No rating available</p>
        <p className="text-sm text-gray-400">Complete the analysis to get a detailed rating</p>
      </div>
    </div>
  );

  const enhancedRating = TextFormatter.enhanceResumeRating(rating);
  
  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-center space-x-3">
        <div className="w-10 h-10 bg-indigo-600 rounded-lg flex items-center justify-center">
          <BarChart3 className="w-5 h-5 text-white" />
        </div>
        <div>
          <h3 className="text-xl font-semibold text-gray-900">Professional Resume Rating</h3>
          <p className="text-sm text-gray-600">AI-powered analysis based on industry standards</p>
        </div>
      </div>

      {/* Overall Grade Card */}
      <div className={`p-8 rounded-2xl border-2 ${enhancedRating.gradeInfo.bgColor} ${enhancedRating.gradeInfo.borderColor}`}>
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center space-x-4 mb-3">
              <div className={`text-6xl font-bold ${enhancedRating.gradeInfo.textColor}`}>
                {enhancedRating.gradeInfo.letter}
              </div>
              <div>
                <h4 className="text-2xl font-bold text-gray-900">{enhancedRating.gradeInfo.label}</h4>
                <p className="text-lg text-gray-600">{enhancedRating.gradeInfo.description}</p>
              </div>
            </div>
          </div>
          <div className="text-right">
            <div className="text-5xl font-bold text-gray-900 mb-2">
              {rating.totalScore}<span className="text-3xl text-gray-500">/10</span>
            </div>
            <div className={`inline-flex px-4 py-2 rounded-full text-sm font-medium ${enhancedRating.gradeInfo.bgColor} ${enhancedRating.gradeInfo.textColor} border ${enhancedRating.gradeInfo.borderColor}`}>
              {enhancedRating.percentages.overall}% Score
            </div>
          </div>
        </div>
        
        {/* Progress Bar */}
        <div className="mt-6">
          <div className="w-full bg-white rounded-full h-4 shadow-inner">
            <div 
              style={{ width: `${enhancedRating.percentages.overall}%` }}
              className={`h-4 rounded-full transition-all duration-1000 bg-gradient-to-r ${
                enhancedRating.percentages.overall >= 90 ? 'from-green-500 to-emerald-600' :
                enhancedRating.percentages.overall >= 70 ? 'from-blue-500 to-indigo-600' :
                enhancedRating.percentages.overall >= 50 ? 'from-yellow-500 to-orange-500' :
                'from-red-500 to-red-600'
              }`}
            ></div>
          </div>
        </div>
      </div>

      {/* Performance Insights */}
      {enhancedRating.insights && (
        <div className="grid gap-4">
          {enhancedRating.insights.map((insight, index) => (
            <div key={index} className={`p-4 rounded-lg border-l-4 ${
              insight.type === 'positive' || insight.type === 'success' ? 'bg-green-50 border-green-400' :
              insight.type === 'warning' ? 'bg-yellow-50 border-yellow-400' :
              insight.type === 'critical' ? 'bg-red-50 border-red-400' :
              'bg-blue-50 border-blue-400'
            }`}>
              <p className={`font-medium ${
                insight.type === 'positive' || insight.type === 'success' ? 'text-green-800' :
                insight.type === 'warning' ? 'text-yellow-800' :
                insight.type === 'critical' ? 'text-red-800' :
                'text-blue-800'
              }`}>
                {insight.text}
              </p>
            </div>
          ))}
        </div>
      )}

      {/* Detailed Category Breakdown */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {[
          { key: 'contentQuality', label: 'Content Quality', icon: '📝', description: 'Relevance and impact of content' },
          { key: 'structureOrganization', label: 'Structure & Organization', icon: '🏗️', description: 'Layout and flow' },
          { key: 'formattingDesign', label: 'Formatting & Design', icon: '🎨', description: 'Visual presentation' },
          { key: 'impactLanguage', label: 'Impact & Language', icon: '🎯', description: 'Action verbs and results' },
          { key: 'atsCompatibility', label: 'ATS Compatibility', icon: '🤖', description: 'Applicant tracking systems' }
        ].map((category) => {
          const score = rating[category.key] || 0;
          const percentage = enhancedRating.percentages[category.key] || 0;
          
          return (
            <div key={category.key} className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm hover:shadow-md transition-all duration-300">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-gray-50 rounded-lg flex items-center justify-center text-xl">
                    {category.icon}
                  </div>
                  <div>
                    <h4 className="font-semibold text-gray-900">{category.label}</h4>
                    <p className="text-sm text-gray-600">{category.description}</p>
                  </div>
                </div>
                <div className={`px-3 py-1 rounded-lg text-sm font-bold ${
                  score >= 2 ? 'bg-green-100 text-green-800' :
                  score >= 1 ? 'bg-yellow-100 text-yellow-800' :
                  'bg-red-100 text-red-800'
                }`}>
                  {score}/2
                </div>
              </div>
              
              {/* Enhanced Progress Bar */}
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Performance</span>
                  <span className="font-semibold text-gray-900">{percentage}%</span>
                </div>
                <div className="relative w-full bg-gray-200 rounded-full h-3">
                  <div 
                    style={{ width: `${percentage}%` }}
                    className={`h-3 rounded-full transition-all duration-700 ${
                      score >= 2 ? 'bg-gradient-to-r from-green-400 to-green-600' :
                      score >= 1 ? 'bg-gradient-to-r from-yellow-400 to-yellow-600' :
                      'bg-gradient-to-r from-red-400 to-red-600'
                    }`}
                  ></div>
                  {/* Score indicator */}
                  <div 
                    style={{ left: `${Math.max(percentage - 2, 0)}%` }}
                    className="absolute top-0 w-1 h-3 bg-white rounded-full shadow-md"
                  ></div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Improvement Recommendations */}
      {enhancedRating.categorizedImprovements && (
        <div className="space-y-6">
          <h4 className="text-lg font-semibold text-gray-900">Improvement Roadmap</h4>
          
          {/* Critical Items */}
          {enhancedRating.categorizedImprovements.critical.length > 0 && (
            <div className="bg-red-50 border border-red-200 rounded-xl p-6">
              <h5 className="font-semibold text-red-800 mb-3 flex items-center">
                <div className="w-5 h-5 bg-red-500 rounded-full mr-3 flex items-center justify-center">
                  <AlertTriangle className="w-3 h-3 text-white" />
                </div>
                Critical Issues ({enhancedRating.categorizedImprovements.critical.length})
              </h5>
              <div className="space-y-2">
                {enhancedRating.categorizedImprovements.critical.map((item, index) => (
                  <div key={index} className="flex items-start space-x-3">
                    <div className="w-2 h-2 bg-red-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p className="text-red-800 text-sm leading-relaxed">{item}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Important Items */}
          {enhancedRating.categorizedImprovements.important.length > 0 && (
            <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-6">
              <h5 className="font-semibold text-yellow-800 mb-3 flex items-center">
                <div className="w-5 h-5 bg-yellow-500 rounded-full mr-3 flex items-center justify-center">
                  <Lightbulb className="w-3 h-3 text-white" />
                </div>
                Important Improvements ({enhancedRating.categorizedImprovements.important.length})
              </h5>
              <div className="space-y-2">
                {enhancedRating.categorizedImprovements.important.map((item, index) => (
                  <div key={index} className="flex items-start space-x-3">
                    <div className="w-2 h-2 bg-yellow-500 rounded-full mt-2 flex-shrink-0"></div>
                    <p className="text-yellow-800 text-sm leading-relaxed">{item}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Next Steps */}
          {enhancedRating.performance.nextSteps && enhancedRating.performance.nextSteps.length > 0 && (
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-6">
              <h5 className="font-semibold text-blue-800 mb-3 flex items-center">
                <div className="w-5 h-5 bg-blue-500 rounded-full mr-3 flex items-center justify-center">
                  <TrendingUp className="w-3 h-3 text-white" />
                </div>
                Recommended Next Steps
              </h5>
              <div className="space-y-2">
                {enhancedRating.performance.nextSteps.map((step, index) => (
                  <div key={index} className="flex items-start space-x-3">
                    <div className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center text-white text-xs font-bold flex-shrink-0">
                      {index + 1}
                    </div>
                    <p className="text-blue-800 text-sm leading-relaxed">{step}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

// Job Recommendations component with structured display
const JobRecommendations = ({ content }) => {
  if (!content) return (
    <div className="flex items-center justify-center py-12">
      <div className="text-center">
        <Target className="w-12 h-12 text-gray-400 mx-auto mb-3" />
        <p className="text-gray-500 font-medium">No job recommendations available</p>
        <p className="text-sm text-gray-400">Upload a resume to get job suggestions</p>
      </div>
    </div>
  );

  const jobData = TextFormatter.formatJobRecommendations(content);
  
  if (jobData.total === 0) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="text-center">
          <Target className="w-12 h-12 text-gray-400 mx-auto mb-3" />
          <p className="text-gray-500 font-medium">Unable to generate job recommendations</p>
          <p className="text-sm text-gray-400">Please try uploading a different resume</p>
        </div>
      </div>
    );
  }

  // Generate LinkedIn search URLs for each job title
  const generateJobSearchUrl = (jobTitle, location = 'United States') => {
    const params = new URLSearchParams({
      keywords: jobTitle,
      location: location,
      f_TPR: 'r86400', // Last 24 hours
      f_JT: 'F' // Full-time
    });
    return `https://www.linkedin.com/jobs/search?${params.toString()}`;
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 bg-purple-600 rounded-lg flex items-center justify-center">
            <Target className="w-5 h-5 text-white" />
          </div>
          <div>
            <h3 className="text-xl font-semibold text-gray-900">Job Recommendations</h3>
            <p className="text-sm text-gray-600">{jobData.total} positions across {jobData.categories.length} categories</p>
          </div>
        </div>
        <div className="flex items-center space-x-3">
          <a
            href="/job-scraper"
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2 text-sm"
          >
            <Target className="w-4 h-4" />
            Find Real Jobs
          </a>
        </div>
      </div>

      {/* Info banner about LinkedIn search */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <div className="flex items-start gap-3">
          <Target className="w-5 h-5 text-blue-600 mt-0.5" />
          <div>
            <h4 className="text-sm font-medium text-blue-800 mb-1">
              Smart Job Search Links
            </h4>
            <p className="text-sm text-blue-700">
              Each job title below includes a direct LinkedIn search link. Click "Search LinkedIn" to find real job postings for that position.
            </p>
          </div>
        </div>
      </div>

      <div className="grid gap-6">
        {jobData.categories.map((category, index) => (
          <div key={index} className="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-xl p-6 border border-purple-100">
            <div className="mb-4">
              <h4 className="text-lg font-semibold text-gray-900 mb-2">{category.name}</h4>
              {category.description && (
                <p className="text-sm text-gray-600 mb-3">{category.description}</p>
              )}
              <div className="flex items-center text-sm text-purple-600">
                <span className="font-medium">{category.jobs.length} positions</span>
              </div>
            </div>
            
            <div className="grid gap-3">
              {category.jobs.map((job, jobIndex) => (
                <div key={jobIndex} className="bg-white rounded-lg p-4 border border-gray-200 hover:border-purple-300 transition-colors">
                  <div className="flex items-center justify-between">
                    <div className="flex items-start space-x-3 flex-1">
                      <div className="flex-shrink-0 w-2 h-2 bg-purple-600 rounded-full mt-2"></div>
                      <div className="flex-1">
                        <h5 className="font-medium text-gray-900">{job}</h5>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2 ml-4">
                      <a
                        href={generateJobSearchUrl(job)}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="px-3 py-1.5 bg-blue-100 text-blue-700 rounded-md hover:bg-blue-200 transition-colors flex items-center gap-1 text-xs font-medium"
                        title={`Search for ${job} jobs on LinkedIn`}
                      >
                        <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 24 24">
                          <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                        </svg>
                        Search LinkedIn
                      </a>
                      <a
                        href={`https://www.google.com/search?q=${encodeURIComponent(job + ' jobs')}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="px-3 py-1.5 bg-gray-100 text-gray-700 rounded-md hover:bg-gray-200 transition-colors flex items-center gap-1 text-xs font-medium"
                        title={`Search for ${job} jobs on Google`}
                      >
                        <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 24 24">
                          <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 6.62 5.367 11.987 11.987 11.987s11.987-5.367 11.987-11.987C23.971 5.367 18.604.001 12.017.001zM8.68 17.704c-1.477 0-2.678-1.201-2.678-2.678s1.201-2.678 2.678-2.678 2.678 1.201 2.678 2.678-1.201 2.678-2.678 2.678zm6.646 0c-1.477 0-2.678-1.201-2.678-2.678s1.201-2.678 2.678-2.678 2.678 1.201 2.678 2.678-1.201 2.678-2.678 2.678z"/>
                        </svg>
                        Google Jobs
                      </a>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Additional job search resources */}
      <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
        <h4 className="text-lg font-semibold text-gray-900 mb-4">Explore More Job Opportunities</h4>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <a
            href="/job-scraper"
            className="flex items-center p-4 bg-white rounded-lg border border-gray-200 hover:border-blue-300 hover:shadow-sm transition-all group"
          >
            <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center mr-3 group-hover:bg-blue-200 transition-colors">
              <Target className="w-5 h-5 text-blue-600" />
            </div>
            <div>
              <h5 className="font-medium text-gray-900">AI Job Finder</h5>
              <p className="text-sm text-gray-600">Smart job search with real LinkedIn data</p>
            </div>
          </a>
          
          <a
            href="https://www.linkedin.com/jobs/"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center p-4 bg-white rounded-lg border border-gray-200 hover:border-blue-300 hover:shadow-sm transition-all group"
          >
            <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center mr-3 group-hover:bg-blue-200 transition-colors">
              <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 24 24">
                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
              </svg>
            </div>
            <div>
              <h5 className="font-medium text-gray-900">LinkedIn Jobs</h5>
              <p className="text-sm text-gray-600">Browse all LinkedIn job listings</p>
            </div>
          </a>

          <a
            href="https://www.indeed.com/"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center p-4 bg-white rounded-lg border border-gray-200 hover:border-blue-300 hover:shadow-sm transition-all group"
          >
            <div className="w-10 h-10 bg-green-100 rounded-lg flex items-center justify-center mr-3 group-hover:bg-green-200 transition-colors">
              <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm5.568 14.034c-.184.4-.568.68-1.014.74-.436.058-.89-.06-1.25-.325-.38-.28-.664-.705-.788-1.188-.13-.5-.13-1.035 0-1.535.124-.483.408-.908.788-1.188.36-.265.814-.383 1.25-.325.446.06.83.34 1.014.74.09.196.09.424 0 .62-.184.4-.568.68-1.014.74-.436.058-.89-.06-1.25-.325-.38-.28-.664-.705-.788-1.188-.13-.5-.13-1.035 0-1.535.124-.483.408-.908.788-1.188.36-.265.814-.383 1.25-.325.446.06.83.34 1.014.74.09.196.09.424 0 .62z"/>
              </svg>
            </div>
            <div>
              <h5 className="font-medium text-gray-900">Indeed</h5>
              <p className="text-sm text-gray-600">Search jobs across multiple sources</p>
            </div>
          </a>
        </div>
      </div>
    </div>
  );
};

// Professional Sections Renderer - Clean and minimal
const StructuredSectionsRenderer = ({ content }) => (
  <div className="space-y-8">
    {content.map((section, index) => (
      <div key={index} className="border-b border-gray-100 pb-6 last:border-b-0">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">
          {section.title}
        </h3>
        <div className="space-y-2">
          {section.items.map((item, itemIndex) => (
            <div key={itemIndex} className="flex items-start space-x-3">
              <div className="flex-shrink-0 w-1.5 h-1.5 bg-blue-600 rounded-full mt-2.5"></div>
              <p className="text-gray-700 leading-relaxed flex-1">
                {item.content}
              </p>
            </div>
          ))}
        </div>
      </div>
    ))}
  </div>
);

// Professional List Renderer - Clean categorized content
const EnhancedListRenderer = ({ content }) => (
  <div className="space-y-6">
    {Object.entries(content).map(([category, items], index) => (
      <div key={index} className="border-b border-gray-100 pb-6 last:border-b-0">
        {category !== 'general' && (
          <h4 className="text-base font-medium text-gray-900 mb-3 capitalize">
            {category.charAt(0).toUpperCase() + category.slice(1)}
          </h4>
        )}
        <div className="space-y-2">
          {items.map((item, itemIndex) => (
            <div key={itemIndex} className="flex items-start space-x-3">
              <div className="flex-shrink-0 w-1.5 h-1.5 bg-blue-600 rounded-full mt-2.5"></div>
              <p className="text-gray-700 leading-relaxed flex-1">
                {item.content}
              </p>
            </div>
          ))}
        </div>
      </div>
    ))}
  </div>
);

// Professional Paragraph Renderer - Clean and simple
const EnhancedParagraphRenderer = ({ content }) => (
  <div className="space-y-3">
    {content.map((paragraph, index) => (
      <div key={index} className="flex items-start space-x-3">
        <div className="flex-shrink-0 w-1.5 h-1.5 bg-blue-600 rounded-full mt-2.5"></div>
        <p className="text-gray-700 leading-relaxed flex-1">
          {paragraph.content}
        </p>
      </div>
    ))}
  </div>
);

// Enhanced content formatter with structured content support
const FormattedContent = ({ content }) => {
  if (!content) return (
    <div className="flex items-center justify-center py-12">
      <div className="text-center">
        <FileText className="w-16 h-16 mx-auto mb-4 text-gray-300" />
        <p className="text-gray-500 text-lg">No content available</p>
      </div>
    </div>
  );

  // Use enhanced structured content parsing
  const structuredContent = TextFormatter.parseStructuredContent(content);
  
  // Render based on content structure type
  if (structuredContent.type === 'sections') {
    return <StructuredSectionsRenderer content={structuredContent.content} />;
  } else if (structuredContent.type === 'enhanced_list') {
    return <EnhancedListRenderer content={structuredContent.content} />;
  } else if (structuredContent.type === 'enhanced_paragraphs') {
    return <EnhancedParagraphRenderer content={structuredContent.content} />;
  }

  // Fallback to original parsing for simple content
  const parseContent = (text) => {
    if (typeof text !== 'string') return [{ type: 'text', content: String(text) }];

    // Pre-process text using dynamic content filtering
    const cleanText = TextFormatter.filterUnwantedContent(text)
      // Clean standalone ### markers that aren't headers
      .replace(/^###\s*$/gm, '')
      // Clean up excessive whitespace and empty lines
      .replace(/^\s*$/gm, '')
      .replace(/\n{3,}/g, '\n\n')
      .trim();

    const elements = [];
    const lines = cleanText.split('\n').filter(line => line.trim());

    lines.forEach((line, index) => {
      const trimmed = line.trim();
      
      // Horizontal rules (---, ***, ___)
      if (trimmed.match(/^(-{3,}|\*{3,}|_{3,})$/)) {
        elements.push({ 
          type: 'separator'
        });
      }
      // Section headers (numbered or ###)
      else if (trimmed.match(/^(#{1,6}\s+|[0-9]+\.\s*).+/)) {
        const headerText = trimmed.replace(/^(#{1,6}\s+|[0-9]+\.\s*)/, '');
        const level = trimmed.startsWith('#') ? (trimmed.match(/^#+/)[0].length) : 1;
        elements.push({ 
          type: 'header', 
          content: headerText, 
          level: Math.min(level, 3),
          id: `section-${index}`
        });
      }
      // Bullet points
      else if (trimmed.match(/^[-•*]\s+/)) {
        elements.push({ 
          type: 'bullet', 
          content: trimmed.replace(/^[-•*]\s+/, '') 
        });
      }
      // Key-value pairs (Label: Content)
      else if (trimmed.match(/^[^:]+:\s+/)) {
        const [, key, value] = trimmed.match(/^([^:]+):\s*(.*)/) || [];
        if (key && value) {
          elements.push({ 
            type: 'keyvalue', 
            key: key.trim(), 
            value: value.trim() 
          });
        }
      }
      // Regular paragraphs
      else if (trimmed.length > 0) {
        // Split long paragraphs into sentences for better readability
        const sentences = trimmed.split(/(?<=[.!?])\s+/).filter(s => s.trim());
        if (sentences.length > 2) {
          sentences.forEach(sentence => {
            elements.push({ 
              type: 'text', 
              content: sentence.trim() 
            });
          });
        } else {
          elements.push({ 
            type: 'text', 
            content: trimmed 
          });
        }
      }
    });

    return elements;
  };

  // Format text with inline styling (bold, italic, etc.)
  const formatInlineText = (text) => {
    if (!text) return text;
    
    // Split text to preserve bold and italic formatting
    const parts = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)/g);
    
    return parts.map((part, index) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={index} className="font-semibold text-gray-900">{part.slice(2, -2)}</strong>;
      } else if (part.startsWith('*') && part.endsWith('*')) {
        return <em key={index} className="italic text-gray-700">{part.slice(1, -1)}</em>;
      } else if (part.startsWith('`') && part.endsWith('`')) {
        return <code key={index} className="bg-gray-100 text-gray-800 px-1.5 py-0.5 rounded text-sm font-mono">{part.slice(1, -1)}</code>;
      }
      return part;
    });
  };

  const elements = parseContent(content);

  return (
    <div className="prose prose-gray max-w-none">
      <div className="space-y-4">
        {elements.map((element, index) => {
          switch (element.type) {
            case 'header':
              const HeaderTag = `h${Math.min(element.level + 2, 6)}`;
              const headerClasses = {
                1: 'text-xl font-bold text-gray-900 mb-3 pb-2 border-b border-gray-200',
                2: 'text-lg font-semibold text-gray-800 mb-2',
                3: 'text-base font-medium text-gray-800 mb-2'
              };
              
              return (
                <div key={index} className="mt-6 first:mt-0">
                  <HeaderTag className={headerClasses[element.level] || headerClasses[3]}>
                    {formatInlineText(element.content)}
                  </HeaderTag>
                </div>
              );

            case 'bullet':
              return (
                <div key={index} className="flex items-start space-x-3 py-1">
                  <div className="flex-shrink-0 w-1.5 h-1.5 bg-blue-600 rounded-full mt-2.5"></div>
                  <p className="text-gray-700 leading-relaxed flex-1">
                    {formatInlineText(element.content)}
                  </p>
                </div>
              );

            case 'keyvalue':
              return (
                <div key={index} className="py-2">
                  <div className="bg-gray-50 rounded-lg p-4 border-l-4 border-blue-500">
                    <dt className="font-medium text-gray-900 mb-1">
                      {formatInlineText(element.key)}
                    </dt>
                    <dd className="text-gray-700 leading-relaxed">
                      {formatInlineText(element.value)}
                    </dd>
                  </div>
                </div>
              );

            case 'separator':
              return (
                <hr key={index} className="my-6 border-0 h-px bg-gradient-to-r from-transparent via-gray-300 to-transparent" />
              );

            case 'text':
              return (
                <p key={index} className="text-gray-700 leading-relaxed py-1">
                  {formatInlineText(element.content)}
                </p>
              );

            default:
              return (
                <p key={index} className="text-gray-700 leading-relaxed py-1">
                  {formatInlineText(element.content)}
                </p>
              );
          }
        })}
      </div>
    </div>
  );
};



export default ResumeAnalyzer;